[package]
name = "api-rust"
version = "0.1.0"
authors = ["MrRojas <rojasarmando260@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
